import Head from 'next/head';
import { useFormik } from 'formik';
import * as Yup from 'yup';
import Router from 'next/router';
import { motion as m } from 'framer-motion';

export default function Home() {
  //Formik logic
  const formik = useFormik({
    initialValues: {
      name: '',
      email: '',
      country: 'United Kingdom',
      terms: '',
    },
    //validate form
    validationSchema: Yup.object().shape({
      name: Yup.string()
        .max(20, 'Name must be max 20 characters')
        .required('Name is required'),
      email: Yup.string()
        .email('Invalid email address')
        .required('Email is required'),
      terms: Yup.array().required('You must accept our terms of service in order to continue')
    }),
    //Submit form
    onSubmit: (values) => {
      console.log(values)
      Router.push({pathname: '/success', query: values});
    },
  });

  return (
    <m.div 
      initial={{opacity: 0}} 
      animate={{opacity: 1}}
      exit={{ opacity: 0}}
      className='absolute w-full'
      >
      <Head>
        <title>React-form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='h-screen flex items-center justify-center'>
        <form
          onSubmit={formik.handleSubmit} 
          className='bg-white flex rounded-3xl sm:w-4/5 md:w-3/5 xl:w-1/2'
        >
          <div className='flex-1 text-gray-700 p-20'>
            <h1 className='text-3xl pb-2'>Lets get started👋</h1>
            <p className=' text-lg text-gray-500'>
              Hello and welcome, in order to begin using our services please fill out the form below.
            </p>
            <div className='mt-6'>
              {/* Input field for name */}
              <div className='pb-4'>
                <label className={`block text-sm pb-2 ${formik.errors.name ? 'text-red-500' : ''}`} htmlFor="name">
                  {formik.touched.name && formik.errors.name ? formik.errors.name : 'Name'}
                </label>
                <input className='border-2 border-gray-500 p-2 rounded-full w-full focus:border-teal-500 focus:ring-teal-500'
                       type="text" 
                       name='name' 
                       value={formik.values.name}
                       onChange={formik.handleChange}
                       onBlur={formik.handleBlur}
                       placeholder='Enter your name'
                />
              </div>
               {/* Input field for email */}
               <div className='pb-4'>
                <label className={`block text-sm pb-2 ${formik.touched.email && formik.errors.email ? 'text-red-500' : ''}`} htmlFor="email">
                  {formik.touched.email && formik.errors.email ? formik.errors.email : 'Email'}
                </label>
                <input className='border-2 border-gray-500 p-2 rounded-full w-full focus:border-teal-500 focus:ring-teal-500'
                       type="email" 
                       name='email' 
                       placeholder='Enter your email'
                       value={formik.values.email}
                       onChange={formik.handleChange}
                       onBlur={formik.handleBlur}
                />
              </div>
               {/* Input field for country */}
               <div className='pb-4'>
                <label className='block text-sm pb-2' htmlFor="country">
                  Select Country
                </label>
                <select className='border-2 border-gray-500 p-2 rounded-3xl w-1/2 focus:border-teal-500 focus:ring-teal-500'
                        name='country' 
                        value={formik.values.country}
                        onChange={formik.handleChange}
                        placeholder='Enter your email'
                >
                  <option>United States</option>
                  <option>Bulgaria</option>
                  <option>Germany</option>
                  <option>United Kingdom</option>
                </select>
              </div>
              {/* Terms of service */}
              <div className='pb-4'>
                <label className={`block text-sm pb-2 ${formik.touched.terms && formik.errors.terms ? 'text-red-500' : ''}`} htmlFor="terms">
                  {formik.touched.terms && formik.errors.terms ? formik.errors.terms : 'Terms of Service'}
                </label>
                <div className='flex items-center gap-2'>
                  <input 
                    type="checkbox" 
                    name='terms' 
                    value='checked'
                    onChange={formik.handleChange}
                    className='h-5 w-5 text-teal-500 border-2 focus:border-teal-500 focus:ring-teal-500'
                  />
                  <p className='text-sm text-gray-500'>
                    I agree to the Terms and Service that my data will be taken and sold.
                  </p>
                </div>
              </div>
              <button 
                type='submit' 
                className='bg-teal-500 text-md text-white py-3 mt-6 rounded-full w-full' 
              >
                Start Learning Today
              </button>
            </div>
          </div>
        </form>
      </main>
    </m.div>
  )
}
